### ISSUE TITLE
Webmachine drops http/1.1 connections on POST request failure when tracing is enabled

### ISSUE THREAD

**Issue by sdebnath** [webmachine/webmachine#232] opened 2015-01-16 04:41 UTC
I have a small easy test case that repros consistently. I have a small API server built using Webmachine that is responding to REST clients. The test clients are written in erlang using eunit.

**Issue**

Erlang's httpc by default uses HTTP/1.1 to open connections with the server so we are expecting connections to be persistent regardless of responses from the server. With the latest Webmachine code and Erlang R17, turns out that enabling tracing and having 2 sequential failed (401 unauthorized) POST requests results in HTTP/1.1 connections being dropped "**error:{badmatch,{error,socket_closed_remotely}}." This is not the case when 2 similar GET requests fail in the same connection.

**Repro**

Sample webmachine code with eunit test repro tarball [[Download]](http://shawn.sdf.org/webmachine_bug.tar.bz2)

In the eunit test, we are testing a few different scenarios:

1) Two POST calls expecting HTTP 401s with inets app being stopped and restarted after each call, i.e., force a new connection. 
2) Two GET calls expecting HTTP 401s without restarting inets, i.e., reuse the same connection after a failed GET attempt in the same connection.
3) Two POST calls expecting HTTP 401s without restarting inets, i.e., reuse the same connection after a failed POST attempt in the same connection.

Test 1 and 2 have a 100% success rate, unfortunately, test 3 fails 100% of the time. (If it passes for you the first run, just retry it in eunit a couple of times).

After first trying to point the finger at httpc, suggestions on erlang-questions to try HTTP/1.0 instead of HTTP/1.1 immediately identified that the client was not the issue and pointed the server either mochiweb or webmachine to be at fault. With trying to get a clean repro ready, I found out that it was in fact enabling tracing that is causing the issue. In src/test_resource.erl init/1, you can switch tracing on and off and you will see the connections not being dropped.

**Version**
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Webmachine - latest from github

**Link to erlang-questions thread**
discussion thread: http://erlang.org/pipermail/erlang-questions/2015-January/082654.html
message with the workaround: http://erlang.org/pipermail/erlang-questions/2015-January/082656.html

**Output**

```
3> c(seq_post_tests).                    
{ok,seq_post_tests}
4> eunit:test(seq_post_tests, [verbose]).
======================== EUnit ========================
module 'seq_post_tests'
  seq_post_tests: separate_inets_per_call_test...
=INFO REPORT==== 15-Jan-2015::20:05:58 ===
    application: inets
    exited: stopped
    type: temporary

=INFO REPORT==== 15-Jan-2015::20:05:58 ===
    application: inets
    exited: stopped
    type: temporary
[0.033 s] ok
  seq_post_tests: same_inets_for_get_calls_test...
=INFO REPORT==== 15-Jan-2015::20:05:58 ===
    application: inets
    exited: stopped
    type: temporary
[0.017 s] ok
  seq_post_tests: same_inets_for_post_calls_test...*failed*
in function seq_post_tests:same_inets_for_post_calls_test/0 (seq_post_tests.erl, line 58)
**error:{badmatch,{error,socket_closed_remotely}}


  [done in 0.068 s]
=======================================================
  Failed: 1.  Skipped: 0.  Passed: 2.
error
5> 


```

**Comment by etrepum** [comment] 2015-01-16 17:04
This appears to be a timing related issue, I can reproduce this as-is but not with a larger body:

``` erlang
-define(SAMPLE_JSON_CONTENT, "{\"hello\":\"world" ++ string:copies(" ", 8192) ++ "\"}").
```

I think what's happening is:
- httpc sends the first request in a single packet and gets an immediate response from the server.
- The server closes the connection between requests because it did not read the body from the first request so it must close the connection.
- The client assumes the connection is still open because the first request was sent in its entirety and a full response was received.
- The client gets a socket_closed_remotely error when trying to send the second request, because the socket has been closed since the first request was complete.

It's possible that including a "Connection: close" header in the _response_ would work around this issue, but ultimately it's httpc's fault for trying to send a request on a closed socket and not just opening a new one and retrying.

**Comment by etrepum** [comment] 2015-01-16 17:22
It appears that the code to handle creating and sending the response is entirely separate between mochiweb and webmachine, so a workaround in one wouldn't do anything for the other.

**Comment by sdebnath** [comment] 2015-01-16 17:53
I am not sure that's the case. That would not explain the behavior where disabling tracing enables the same test code with the same 401 error (request body not being read) work just fine. With tracing enabled in test_resource (init/1), and putting in the larger sample body still repros the issue.

**Comment by etrepum** [comment] 2015-01-16 18:37
Doesn't repro with the larger body here, regardless of tracing setting.

**Comment by sdebnath** [comment] 2015-01-16 18:57
Okay - could have been my lack of sleep - but doesn't repro with the large payload. So what could be going wrong with tracing that's breaking requests without large chunks of data (norm for many rest requests)?

**Comment by etrepum** [comment] 2015-01-16 19:12
I don't know why tracing should make a difference, but it could be some sort of timing issue or race condition in httpc. Adding a non-zero amount of sleep between the calls makes it impossible for me to reproduce as well. Remove the comment and it'll pass.

``` erlang
same_inets_for_post_calls_test() ->

    inets:start(),

    lists:foreach(fun (_) ->
            {ok, {{_, Status1, _}, _, _}} =
                httpc:request(post, {?URL, [], ?CONTENT_TYPE_JSON, ?SAMPLE_JSON_CONTENT}, [], []),
            ?assertEqual(401, Status1),
            ok %%, receive after 1 -> ok end
        end,
        lists:seq(1, 100)),

    inets:stop().
```

**Comment by sdebnath** [comment] 2015-01-16 19:21
Yeah, for my initial post on erlang-questions, I added debug logging to see the response headers/body and that caused it not repro as well. However, I still believe it has something to do with the server side as disabling tracing causes the 2 sequential posts to work. What's a good way, if there is any, to get more information on the server side to see why connections are being dropped in one case and not the other. The instructions to debug mochiweb didn't work so well with webmachine (http://stackoverflow.com/questions/1816329/mochiweb-debug-like-ejabberd-debug).

**Comment by sdebnath** [comment] 2015-01-16 19:30
The regular trace for the failed attempt: http://pastebin.com/Zg9GcJPF

**Comment by etrepum** [comment] 2015-01-16 19:42
The connection is being dropped because the response to the request is sent without the body of the request being read. The server does not bother reading the body because it knows as soon as it sees the headers that the request will fail, so it fails the request and closes the socket.

Like I said before, the only thing the server _could_ do differently is send a "Connection: close" header in that response, which might help, but this is certainly an issue with httpc either way. The socket could get closed for plenty of reasons between requests and httpc should pick up on that but it appears to have some sort of race condition here.

Tracing is likely "causing" the issue because there's a little more of a delay between finishing the response (thus returning a value from httpc:request)  and closing the socket.

**Comment by beerriot** [comment] 2023-02-15 22:04
The pastebins and tarballs linked from this issue are all gone, but I was able to reproduce the error by massaging Bob's code into `decision_core_tests` like so:

```erlang
same_inets_for_post_calls() ->
    put_setting(is_authorized, "Basic realm=decsisioncoretest"),
    put_setting(content_types_accepted, [{"text/plain", accept_text}]),
    put_setting(allowed_methods, ?HTTP_1_1_METHODS),
    put_setting(resource_exists, true),
    lists:foreach(fun (_) ->
            {ok, {{_, Status1, Body}, _, _}} =
                httpc:request(post, {url("post"), [], "text/plain", "{\"hello\":\"world\"}"}, [], []),
            ?assertMatch({401, _}, {Status1, Body}),
            ok
        end,
        lists:seq(1, 100)).
```

> The connection is being dropped because the response to the request is sent without the body of the request being read. The server does not bother reading the body because it knows as soon as it sees the headers that the request will fail, so it fails the request and closes the socket.

This point is exactly on target according to my test runs, and I think that means this is at least partly a duplicate of #168.

I modified the v3b8 decision core code to read the body before responding 401, like so:

```erlang
%% "Authorized?"
decision(v3b8) ->
    case resource_call(is_authorized) of
        true -> d(v3b7);
        {error, Reason} ->
            error_response(Reason);
        {halt, Code}  ->
            respond(Code);
        AuthHead ->
            wrcall({set_resp_header, "WWW-Authenticate", AuthHead}),
            maybe_flush_body_stream(),  %% ADDED
            respond(401)
    end;
```

With that code in place, the test never failed for me. I don't think this can be timing related at this point either. I tried replacing that with a `receive after N -> ok` where I varied N from 0 to 50. I saw the test pass once at 20, but not on a re-run, and all other values failed. The 100-request test eventually got up to three seconds of runtime at N=50 and still failed. At N=100 the test times out. But, with the `maybe_flush_body_stream` in place, the test's runtime is about 100ms.

I also tried using `wrcall({set_resp_header, "Connection", "close"})` instead of the `maybe_flush_body_stream` call, to force a Connection:close header, as Bob suggested. This also caused the test to pass every time I ran it.

I'm not sure I actually want to close this as a duplicate yet, but if #168 gets resolved, this issue seems like it will be resolved as well.

**Closed as completed** 2023-02-20 20:34 UTC
