### ISSUE TITLE
OTP 27's +0.0 and -0.0

### ISSUE THREAD

**Issue by ANoneTypeOn** [webmachine/webmachine#341] opened 2023-10-19 18:39 UTC
Hello. I have a problem while compiling Webmachine under Erlang 26.1 for Riak that is breaking further compilation. I'm using the latest version of the repository 

During compilation process I see next errors:
===> Compiling _build/default/lib/webmachine/src/webmachine_util.erl failed
```_build/default/lib/webmachine/src/webmachine_util.erl:267:18: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.```
```_build/default/lib/webmachine/src/webmachine_util.erl:270:10: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.```
```_build/default/lib/webmachine/src/webmachine_util.erl:275:10: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.```
```_build/default/lib/webmachine/src/webmachine_util.erl:299:9: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.```

**Comment by beerriot** [comment] 2023-10-19 19:58
Hmmm. We were hoping that #340 fixed that. I know you said you're using the latest version, but could you please verify that you've pulled commit 530c1d1, where that patch was merged to main? The column number in the error messages you quoted suggests that you have the old `[0.0]` code, and not the new `[SP] when SP == 0.0` code.

I don't have a 26.1 environment at the moment, and it looks like the setup-beam tool we're using in the test actions might only support up to 25. So I won't be debugging this, if that patch didn't fix it, myself in the near future.

**Comment by beerriot** [comment] 2023-10-21 22:29
I just set up a local OTP 26.1 environment and confirmed that I do not see these warnings on the current main HEAD (530c1d1). I do see them on the previous HEAD (0bdcc77).

But I did see that there was one warning in the v3.1.1 version of mochiweb we were using, so I've submitted #342 to update the dependency to v3.2.1, which has their fix.

**Closed as completed by beerriot** 2023-10-21 22:29 UTC
